---
# tasks file for haproxy

- name: Update haproxy config
  template:
    src: haproxy/haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    backup: yes
    force: yes
  notify: restart services
  tags: configuration

# service check
- debug: msg="haproxy service check status"
  notify: check services
  changed_when: true
  tags: status

