---
# handlers file for sentry

- name: restart sentry
  service:
    name: supervisord.service
    state: restarted
  notify: restart nginx

- name: restart nginx
  service:
    name: nginx.service
    state: restarted
